### PR TITLE
Added new features to improve the repo

### PR DESCRIPTION
**Pull request by thechampagne**
- [x] Script to update the list
- [x] New way to add languages using JSON
- [x] New way to check activity
  * if the repo has not been updated in 6 months it count as Inactive.

How to add new language :
1.  language schema in `languages.json`
```json
{
    "name": "Language-name",
    "description": "Description",
    "url": "repo-url",
    "stars": 0,
    "active": true
}
```
2. run the script

create `.env` file to add github access token.
```
TOKEN=github-access-token
```

`python update.py` * It will update the README from JSON file
`python update.py api` * It will make request to github api, update JSON file then update README

### CODE REVIEW

**Comment by alilleybrinker** [comment]
Hey, just commenting now to say that I've seen this and need to give it a real review. Not forgotten, and I will get to it soon!

**Comment by alilleybrinker** [comment]
I will say that one thing I haven't resolved for myself is whether I want the "Description" field to become whatever's in the About block for a repository, or to try to keep the current by-hand explanations. A number of them currently are briefer or more specific for the context of this list than the description pulled from a repo.

**Comment by alilleybrinker** [comment]
Okay, I've been thinking about it more and I think I want the descriptions to _not_ just be pulled automatically from the repository. Sometimes those descriptions aren't very descriptive, and using them would make the list less useful because people would more likely have to click through to understand what a project is doing.

Some other options include trying to tag repositories in the list based on features or paradigm, but I think that's probably overkill and invites debate about the tagging that distracts from the purpose.

So I think having custom descriptions is the right way to go. If you're willing to rework this PR to implement that, then I'm happy to take another look.

Thanks!

**Comment by thechampagne** [comment]
Done.

**Comment by alilleybrinker** [comment]
Thank you! I think I like the approach, though it appears dependencies aren't bundled up with the script. I'm not _super_ familiar with Python, though I've used `poetry` recently for this purpose. Do you know the standard way to handle this?

**Comment by thechampagne** [comment]
Hey, I don't know if there is a standard way but I found an easy way just type:
```
pip install -r requirements.txt
```
It will install the dependencies.

**Comment by alilleybrinker** [comment]
LGTM! Thanks for working on this!

**Pull request merged**
